"""added cars V

Revision ID: 476eec22f7d2
Revises: ef59ca5e53bc
Create Date: 2022-04-20 19:12:28.011618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '476eec22f7d2'
down_revision = 'ef59ca5e53bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('car', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car', sa.Column('description', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
