"""added cars II

Revision ID: 5ce0ea7b6f08
Revises: 9a2c6ec8168a
Create Date: 2022-04-20 17:44:26.558753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ce0ea7b6f08'
down_revision = '9a2c6ec8168a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car', sa.Column('year', sa.String(length=4), nullable=True))
    op.add_column('car', sa.Column('make', sa.String(length=50), nullable=True))
    op.add_column('car', sa.Column('model', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('car', 'model')
    op.drop_column('car', 'make')
    op.drop_column('car', 'year')
    # ### end Alembic commands ###
